# This file contain definition of meta data information for map
# message. This file was created based on ndt_map_hmt.h
# by Tomasz Kucner

float64 resolution # resolution of the map
float32 center_x   # x coordinate of the map center
float32 center_y   # y coordinate of the map center
float32 center_z   # z coordinate of the map center
float32 size_x     # x size of the grid
float32 size_y     # y size of the grid
float32 size_z     # z size of the grid
